// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"tiktok/internal/biz"
	"tiktok/internal/conf"
	"tiktok/internal/data"
	"tiktok/internal/interfaces"
	"tiktok/internal/server"
	"tiktok/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, database *conf.Database, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewPostgres(database)
	dataDatabase, cleanup, err := data.NewData(database, logger, db)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataDatabase, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userService := service.NewUserService(userUseCase)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	interfacesUserUseCase := _interface.NewUserUseCase(userService, logger)
	httpServer := server.NewHTTPServer(confServer, interfacesUserUseCase, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
